USE [master]
GO

/****** Object:  Database [GraRPG]    Script Date: 2017-06-07 10:24:00 ******/
CREATE DATABASE [GraRPG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GraRPG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\GraRPG.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GraRPG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\GraRPG_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GraRPG] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GraRPG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GraRPG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GraRPG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GraRPG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GraRPG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GraRPG] SET ARITHABORT OFF 
GO

ALTER DATABASE [GraRPG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GraRPG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GraRPG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GraRPG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GraRPG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GraRPG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GraRPG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GraRPG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GraRPG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GraRPG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GraRPG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GraRPG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GraRPG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GraRPG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GraRPG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GraRPG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GraRPG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GraRPG] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GraRPG] SET  MULTI_USER 
GO

ALTER DATABASE [GraRPG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GraRPG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GraRPG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GraRPG] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GraRPG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GraRPG] SET  READ_WRITE 
GO

